Repository GeminiLab/enumerable, pull requests merged in 2024-06, with the labels that each got.

#8 Add GitHub actions to run cargo test
  .github/workflows/ci.yml
Labels: repo

#6 impl ExactSizeIterator for BoolEnumerator
  src/lib.rs
  src/test.rs
Labels: enhancement

#7 impl Enumerable for (A,) and (A, B)
  src/impl_tuple.rs
  src/lib.rs
  src/test.rs
Labels: enhancement

#15 Remove `ResultEnumerator`, use `std::iter::{Chain, Map}` instead for better speed and less code
  src/lib.rs
Labels: enhancement, breaking change

#14 Update the way derive_macro Enumerable creating enumerator for struct
  enumerable_derive/src/lib.rs
  examples/03-struct-tuple.rs
  src/test.rs
Labels: bug, enhancement, breaking change, derive

#19 Add .editorconfig
  .editorconfig
Labels: repo

#18 rustfmt check on CI
  .github/workflows/ci.yml
  .rustfmt.toml
  src/test.rs
Labels: repo

#21 Issues/5 make it possible to derive `enumerable` automatically on `enum`s with enumerable fields
  enumerable_derive/src/lib.rs
  examples/02-enum.rs
  src/lib.rs
  src/test.rs
Labels: enhancement, breaking change, derive

#22 Issues/11 allow programmer to choose the name of the enumerator generated by derive enumerable
  enumerable_derive/src/lib.rs
  src/lib.rs
  src/test.rs
Labels: documentation, derive

#24 Issues/23 use proc macro crate to find correct path to `enumerable`
  .github/workflows/ci.yml
  .idea/enumerable.iml
  Cargo.toml
  enumerable_derive/Cargo.toml
  enumerable_derive/src/lib.rs
  examples/example_crates/crate_alias/Cargo.toml
  examples/example_crates/crate_alias/src/main.rs
  examples/example_crates/run_example_crates.sh
  examples/run_examples.sh
Labels: bug, derive

#17 Enumerable::ENUMERABLE_SIZE
  enumerable_derive/src/lib.rs
  src/impl_tuple.rs
  src/lib.rs
  src/test.rs
Labels: enhancement, breaking change, derive

#30 Issues/26 add an associated constant for the number of possible values of a type implementing `enumerable`
  enumerable_derive/src/lib.rs
  examples/02-enum.rs
  src/impl_tuple.rs
  src/lib.rs
  src/test.rs
Labels: enhancement, breaking change, derive

#31 remove `BoolEnumerator`
  src/lib.rs
Labels: enhancement, breaking change

#32 New examples and docs for v1.0
  README.md
  enumerable_derive/src/lib.rs
  examples/01-basic-and-primitives.rs
  examples/01-builtin.rs
  examples/02-derive-on-enums.rs
  examples/02-enum.rs
  examples/03-derive-on-structs.rs
  examples/03-struct-tuple.rs
  examples/04-option-and-result.rs
  examples/04-option.rs
  examples/05-result.rs
  examples/05-tuples.rs
  examples/06-mix.rs
  examples/06-readme.rs
  examples/07-readme-extended.rs
  examples/README.md
  src/CRATE_DOC.md
  src/impl_built_in.rs
  src/impl_tuple.rs
  src/lib.rs
  src/test.rs
  src/test/mod.rs
  src/test/testee.rs
  src/test/tester.rs
Labels: documentation, enhancement, repo

#33 no_std support
  .idea/enumerable.iml
  enumerable_derive/src/lib.rs
  examples/example_crates/no_std/Cargo.toml
  examples/example_crates/no_std/src/main.rs
  src/impl_built_in.rs
  src/impl_tuple.rs
  src/lib.rs
Labels: breaking change, derive

#34 Release v1.0
  .editorconfig
  .github/workflows/ci.yml
  .idea/enumerable.iml
  .rustfmt.toml
  Cargo.toml
  README.md
  enumerable_derive/Cargo.toml
  enumerable_derive/src/lib.rs
  examples/01-basic-and-primitives.rs
  examples/01-builtin.rs
  examples/02-derive-on-enums.rs
  examples/02-enum.rs
  examples/03-derive-on-structs.rs
  examples/03-struct.rs
  examples/04-option-and-result.rs
  examples/04-option.rs
  examples/05-result.rs
  examples/05-tuples.rs
  examples/06-mix.rs
  examples/06-readme.rs
  examples/07-readme-extended.rs
  examples/README.md
  examples/example_crates/crate_alias/Cargo.toml
  examples/example_crates/crate_alias/src/main.rs
  examples/example_crates/no_std/Cargo.toml
  examples/example_crates/no_std/src/main.rs
  examples/example_crates/run_example_crates.sh
  examples/run_examples.sh
  src/CRATE_DOC.md
  src/impl_built_in.rs
  src/impl_tuple.rs
  src/lib.rs
  src/test.rs
  src/test/mod.rs
  src/test/testee.rs
  src/test/tester.rs
Labels: release

#35 version 1.0.0
  Cargo.toml
Labels: release
